[643] Mint button in bottom balances sheet
compolabs/spark pull request #51
Opened 2024-02-06 23:51 UTC by PaulZhemanov

2024-02-08 13:01 UTC, lzhabo requested changes

2024-02-08 13:01 UTC, lzhabo commented on spark-frontend/src/components/MintButtons.tsx
это плохой подход 

у тебя такие компоненты не должны лежать в папке компонентс, там должны быть только переиспользуемые блоки, как просто кнопка, инпут, логика и клики должны быть в папке страницы

2024-02-08 13:01 UTC, lzhabo commented on spark-frontend/src/components/MintButtons.tsx
да и вообще логика этой кнопки может быть в том же файде, так как она не большая, можно и не выносить в отдельный файл

2024-02-08 13:34 UTC, lzhabo commented on spark-frontend/src/screens/Faucet/MintButtons.tsx
> +    <>
у тебя внутри <> </> только один компонент, тогда тебе надо убрать <> </>

2024-02-08 13:39 UTC, lzhabo requested changes

2024-02-08 13:39 UTC, lzhabo commented on spark-frontend/src/screens/Faucet/MintButtons.tsx
> +            disabled={
вот эту логику можно вытащить в фасет стор и сделать геттером, будет удобно и красиво

2024-02-08 13:39 UTC, lzhabo commented on spark-frontend/src/screens/Faucet/MintButtons.tsx
> +            onClick={() => {
вот это будет красиво вытащить в функцию выше и сделатьпросто ее вызов, типа handleonClick 

и тогда читабельность компонента будет лучше

2024-02-08 13:39 UTC, lzhabo commented on spark-frontend/src/screens/Faucet/TokensFaucetTable.tsx
> +        <TableTitle>Asset</TableTitle>
вот это можно сделать с помощб/ мапы и будет красивее 

типа 

["title1", "title2", "title3"].map(()=><TableTitle>...)

2024-02-09 10:59 UTC, EchoDex commented on spark-frontend/src/screens/Faucet/TokensFaucetTable.tsx
> +  //overflow: scroll;
Надо удалить если не нужно

2024-02-09 11:00 UTC, EchoDex commented on spark-frontend/src/screens/Faucet/TokensFaucetTable.tsx
> +        {["Asset", "Mint amount", "My balance"].map((title, index) => (
Предлагаю этот массив создать вне компонента, чтобы он не пересоздавался постоянно

2024-02-09 11:07 UTC, EchoDex commented on spark-frontend/src/screens/Faucet/TokensFaucetTable.tsx
> +          <Row justifyContent="flex-end">{/*<Button style={{ width: 120 }}>Mint all</Button>*/}</Row>
Если не используется, то удалить

2024-02-09 11:07 UTC, EchoDex commented on spark-frontend/src/stores/FaucetStore.ts
> +    if (token && token.symbol === "ETH") {
Можно упростить как-то так
```typescript
if (!token) return;

if (token.symbol === "ETH") {
...
}

faucetStore.mint(assetId);
```

Так выглядит попроще

2024-02-12 13:03 UTC, merged